# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-16 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('video', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('health_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='database.HealthCard')),
            ],
        ),
    ]
