# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-17 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthstate',
            name='name',
        ),
        migrations.AddField(
            model_name='healthstate',
            name='state_desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
